spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactdb_1
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration