spring:
  profiles:
#   active: flyway-ds0
#   active: flyway-ds1
    active: sharding
  application:
    name: transaction-service
logging:
  level:
    com.example.transactionservice: debug

server:
  port: 9999
